name: 'Hello World'
description: 'Run .NET Core Hello World app!'
inputs:
  who:
    description: 'Who to say hello to'
    required: false
    default: World
runs:
  using: "composite"
  steps: 
    - run: dotnet exec ${{ github.action_path }}/bin/Release/netcoreapp3.1/publish/dotnet-hello-world-action.dll ${{ inputs.who }}
      shell: bash
      env:
        DOTNET_NOLOGO: true
