env:
  DOTNET_NOLOGO: true
  config: Release

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: dotnet new console

    - run: dotnet publish -c ${{ env.config }}

    - run: |
        git checkout -b action
        git add bin/${{ env.config }}
        git push --set-upstream origin action --force
