env:
  DOTNET_NOLOGO: true
  config: Release
  branch: action

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    - uses: dotnet/nbgv@v0.3.1
      with:
        setAllVars: true

    - run: dotnet publish -c ${{ env.config }}

    - run: dotnet run bin/${{ env.config }}/netcoreapp3.1/dotnet-hello-world-action.dll

    - run: |
        git checkout -b ${{ env.branch }}
        git add bin/${{ env.config }}
        git config --global user.email "you@example.com"
        git config --global user.name "Package Publisher"        
        git commit -m "Add built files"
        git push --set-upstream origin ${{ env.branch }} --force
        git tag $TAG_NAME
        git push origin $TAG_NAME
      env:
        TAG_NAME: v${{ env.NBGV_SemVer2 }}

  test:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - uses: jcansdale-test/dotnet-hello-world-action@action
      with:
        who: Moon
