env:
  DOTNET_NOLOGO: true
  config: Release
  branch: v0.1

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: dotnet publish -c ${{ env.config }}

    - run: dotnet run bin/${{ env.config }}/netcoreapp3.1/dotnet-hello-world-action.dll

    - run: |
        git checkout -b ${{ env.branch }}
        git add bin/${{ env.config }}
        git config --global user.email "you@example.com"
        git config --global user.name "Package Publisher"        
        git commit -m "Add built files"
        git push --set-upstream origin ${{ env.branch }} --force

  test:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - uses: jcansdale-test/dotnet-hello-world-action@v0.1
      with:
        who: World
